# Generated by Django 5.1 on 2024-08-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre_usuario', models.CharField(default='', max_length=50, unique=True)),
                ('primer_nombre', models.CharField(default='', max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, default='', max_length=50)),
                ('primer_apellido', models.CharField(default='', max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, default='', max_length=50)),
                ('correo', models.EmailField(default='', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
